### ISSUE TITLE
 Inquiry About SGG Evaluation Code

### ISSUE THREAD

**Issue by slcheng97** [lorjul/fair-psgg#2]
Thank you for your inspiring work!

I attempted to reproduce your results in Table 1, but I could only locate the evaluation code for Predicate Classification. Unfortunately, I couldn’t find the evaluation code for the SGG (Scene Graph Generation) setting in this repository.

Could you please let me know where I can find the SGG evaluation code?

Thank you for your assistance!

**Comment by lorjul** [comment]
Thanks for your interest!

In principle the idea is as follows: use a segmentation model and generate a new PSG dataset (without the relations). Run inference using that dataset using DSFormer. Match the segmentation masks to the ground truth masks and calculate the metrics.

I will upload the related scripts, but it'll take some time to make them available to the public. I'm quite busy at the moment but will come back to you once I've uploaded the scripts.

**Comment by lorjul** [comment]
The evaluation scripts and instructions are now available.
