### ISSUE TITLE
Improve discoverability on HF

### ISSUE THREAD

**Issue by NielsRogge** [lorjul/fair-psgg#3]
Hi @lorjul,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2407.09216 (feel free to claim it). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work  on the hub.

It'd be great to make the dataset available on the 🤗 hub, we can add tags so that people find them when filtering https://huggingface.co/datasets, so that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-username-or-organization/psg")
```

See here for a guide: https://huggingface.co/docs/datasets/image_dataset.

This would make the dataset easier accessible, and also discoverable.

We can then also link the dataset to the paper page.

Let us know if you need any help.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by lorjul** [comment]
Hi Niels,

thanks for reaching out. Having the dataset available on huggingface sounds like a great idea! However, the used dataset is not ours but from here: https://github.com/Jingkang50/OpenPSG
I'm not sure how this is handled at huggingface. I guess it's up to the original authors whether they want their data on huggingface or not?

**Comment by NielsRogge** [comment]
Thanks, have reached out at https://github.com/Jingkang50/OpenPSG/issues/120.

Will close this one.
