### ISSUE TITLE
How to implement singlempo codes in OpenPSG？

### ISSUE THREAD

**Issue by ZHUXUHAN** [lorjul/fair-psgg#8]
dear author, can you provide the  evaluation codes of singlempo in original OpenPSG? By the way, is the singlempo is just same as the general metrics in original OpenPSG for two stage methods. And for the single-stage methods, they unfairly use the multimpo methods? Finally, what test split do you use? the val split or the val+test split, the former has 1000 images and the latter has 2000+ images.

**Comment by ZHUXUHAN** [comment]
We found that the accuracy of the single-stage SingleMPO is higher than MultiMPO. Could you please provide the test code for this? This is very important for us.

**Comment by lorjul** [comment]
You are right, it's missing in the repo! Thanks for pointing it out. I'll add the missing code soon (probably somewhen next week).

**Comment by lorjul** [comment]
I've pushed the `scripts/convert_openpsg.py` utility. You can use it to convert the output of the compared methods from the paper.

We've chosen the following approach: Convert results to desired format such that all methods use the same format. Then, use the evaluate script to calculate the metrics.

If you want to evaluate your own model, I recommend to directly store your output in the expected file format and not use the conversion script above. This gives you more flexibility and is less error prone.

**Comment by ZHUXUHAN** [comment]
Thanks for your answers.
