### ISSUE TITLE
About the metric all_R and img_R?

### ISSUE THREAD

**Issue by ZHUXUHAN** [lorjul/fair-psgg#9]
are the metrics all_R and img_R just the R@k and mR@K metrics?

**Comment by lorjul** [comment]
Both metrics calculate R@k

all_R@k calculates micro R@k, so count all hits over the whole dataset first and divide by the number of ground truth.

img_R@k calculates R@k for each individual image and averages the scores for the final result.

In the literature, the second option (img_R@k) is preferred. all_R@k was just an experiment to see if it makes any difference (there is no significant difference).


For mR@k check out img_mR@k (or all_mR@k if you want the micro version).

I will remove all_R@k from the code to avoid any confusion in the future. Thanks for pointing that out!
